version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: JPHACKS2021_server
    volumes:
      - type: bind
        source: "./"
        target: "/usr/src/app"
    ports:
      - "8000:8000"
    tty: true
